config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "homes#index"
  get "map" => "homes#map"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    get :posts, on: :member
    get :shoppings, on: :member
    get :reviews, on: :member
  end

  resources :posts do
    resource :shoppings, only: [:create, :destroy]
    resource :reviews, only: [:new, :create, :destroy]
    get :reviews, on: :member
    get :ranking, on: :collection
  end

  resources :reviews, only: [:edit, :update]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :shoppings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :genre, presence: true
  validates :rate, numericality: { greater_than_or_equal_to: 1 }
  
  enum genre: [ "ジャンルなし", "キッチン用品", "文具", "衛生・清掃", "洗面・バス", "化粧品", "収納", "電気", "雑貨", "食品", "DIY"]

  mount_uploader :image, ImageUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/shopping.rb
class Shopping < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :shoppings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  mount_uploader :user_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_image])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, only: :map

  def index
  end

  def map
    post_shop_list=Post.pluck(:shop_name).reject(&:blank?)
    review_shop_list=Review.pluck(:shop_name).reject(&:blank?)
    @shop_list=post_shop_list | review_shop_list
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @q = Post.ransack(params[:q])
    @posts=@q.result.page(params[:page]).per(4)
  end

  def show
    @post=Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post=current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path,notice: "新規投稿を完了しました。"
    else
      render :new,alert: "内容に不備があります。確認してもう一度送信してください。"
    end
  end

  def edit
    @post=Post.find(params[:id])
  end

  def update
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path,notice: "投稿の編集を完了しました。"
    else
      render :edit,alert: "内容に不備があります。確認してもう一度送信してください。"
    end
  end

  def destroy
    @post=Post.find(params[:id])
    @post.destroy!
    redirect_to posts_path, alert: "投稿を削除しました。"
  end

  def reviews
    @post=Post.find(params[:id])
    @reviews=Review.where(post_id:@post.id)
  end

  def ranking
    # @ranks=Post.all.sort {|a,b| b.reviews.average(:rate).to_f.round(1) <=> a.reviews.average(:rate).to_f.round(1) }
    @ranks=Post.find(Review.group(:post_id).order('avg(rate) desc').pluck(:post_id))
    # @ranks=Post.find(Review.group(:post_id).order('average_rate desc').average(:rate).pluck(:post_id))
    # score: <%= @post.reviews.average(:rate).to_f.round(1) %>
    
  end

  private 
  
  def post_params
    params.require(:post).permit(:name,:comment,:genre,:shop_name,:rate,:genre,:image,:purchase_num).merge(user_id:current_user.id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_post, except: [:edit,:update]
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create
    @review=Review.new(review_params)
    if @review.save
      redirect_to posts_path,notice: "口コミ投稿を完了しました。"
    else
      redirect_to new_post_reviews_path(@post),alert: "すでに口コミは投稿されています。"
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_edit_params)
      redirect_to posts_path,notice: "口コミ編集を完了しました。"
    else
      render :edit,alert: "内容に不備があります。確認してもう一度送信してください。"
    end
  end

  def destroy
    @review=Review.find_by(user_id: current_user.id, post_id: @post.id)
    @review.destroy!
    redirect_to posts_path, alert: "口コミを削除しました。"
  end

  private 
  
  def review_params
    params.require(:review).permit(:title,:comment,:rate,:shop_name).merge(user_id:current_user.id,post_id:@post.id)
  end

  def review_edit_params
    params.require(:review).permit(:title,:comment,:rate,:shop_name)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create 
    @shopping = Shopping.create(user_id: current_user.id, post_id: @post.id)
  end

  def destroy
    @shopping = Shopping.find_by(user_id: current_user.id, post_id: @post.id)
    @shopping.destroy
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def new_guest
        user = User.guest
        sign_in user
        redirect_to root_path ,notice: "ゲストユーザーとしてログインしました。"
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!

  def posts
    @posts = Post.where(user_id: current_user.id)
  end

  def shoppings
    shoppings = Shopping.where(user_id: current_user.id).pluck(:post_id)
    @shopping_list = Post.find(shoppings) 
  end

  def reviews
    reviews = Review.where(user_id: current_user.id).pluck(:post_id)
    @review_list = Post.find(reviews)
  end

  private
  def set_user
    @user=User.find(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="top_container">
	<br>
	<div class="top_container_text">
		<h2 class="ml-5">100円ショップを</h2>
		<h2 class="mt-4 text-center">もっと楽しく</h2>
		<h2 class="mr-5 mt-4 text-right">もっと便利に</h2>
	</div>
</div>
<div class="explanation_area">
	<h2 class="mb-4">¥100とは</h2>
	<p>誰しも利用したことがある100円ショップ</p>
	<p>当サイトではその100均にスポットを当て</p>
	<p>買って良かった商品やこんな商品があったなど</p>
	<p>情報交換を目的としたサイトです。</p>
</div>
<div class="usage_area">
	<h3 class="my-4" id="usage_title">¥100の使い方</h3>
	<div class="card my-3" style="border: 1px solid black;">
		<div class="row m-0">
			<div class="usage_icon col-2">
				<i class="fas fa-comments fa-4x"></i>
			</div>
			<div class="usage_message col-10">
				<h5>購入した商品のレビューを投稿！</h5>
				実際に自分で購入した商品をレビューしてみよう。購入店舗、購入回数なども入力出来ます。
			</div>
		</div>
	</div>
	<div class="card my-3" style="border: 1px solid black;">
		<div class="row m-0">
			<div class="usage_icon col-2">
				<i class="fas fa-search fa-4x"></i>
			</div>
			<div class="usage_message col-10">
				<h5>みんなのレビューを閲覧！</h5>
				他のユーザーのレビューを見てみよう。新商品や気になる商品に出会えるかも。購入したら口コミを投稿してみよう！
			</div>
		</div>
	</div>
	<div class="card my-3" style="border: 1px solid black;">
		<div class="row m-0">
			<div class="usage_icon col-2">
				<i class="fas fa-shopping-cart fa-4x"></i>
			</div>
			<div class="usage_message col-10">
				<h5>気になった商品をストック！</h5>
				気になる商品を見つけたら買い物リストにストック。次のショッピングの手助けに。
			</div>
		</div>
	</div>
	<div class="card my-3" style="border: 1px solid black;">
		<div class="row m-0">
			<div class="usage_icon col-2">
				<i class="fas fa-crown fa-4x"></i>
			</div>
			<div class="usage_message col-10">
				<h5>商品ランキングをチェック！</h5>
				人気の商品を見てみよう。試したくなる商品に出会えるかも。
			</div>
		</div>
	</div>
	<div class="card my-3" style="border: 1px solid black;">
		<div class="row m-0">
			<div class="usage_icon col-2">
				<i class="fas fa-map-marker-alt fa-4x"></i>
			</div>
			<div class="usage_message col-10">
				<h5>ショップを検索！</h5>
				最寄りのショップを検索しよう！みんなが購入したショップの場所も調べられます。
			</div>
		</div>
	</div>
</div>
<div class="sample_area"> 
	<h3 class="mb-4 text-center">サンプルムービー</h3>

	<div class="embed-responsive embed-responsive-16by9">
		<iframe class="embed-responsive-item" src="画面収録.mp4" allowfullscreen></iframe>
	</div>
</div>

app/views/homes/map.html.erb
<div class="row">
  <div class="col-8">
    <h3 class="text-center mb-3">ショップ検索</h3>
    <div class="text-center mb-4">
      <input id="address" type="text" size="30" placeholder="ショップ名を入力してください。">
      <input type="button" value="検索" onclick="codeAddress()">
      <div class="mt-2" id="display"></div>
    </div>
    <div id='map'></div>
  </div>
  <div class="col-3">
    <p class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      ショップリスト
    </p>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <p style="opacity: 0.5;">(クリックでコピーされます)</p>

      <%@shop_list.each do |name|%>
          <p class="copy_btn dropdown-item" data-clipboard-text="<%=name%>"><%=name%></p>
      <%end%>
    </div>
  </div>
</div>
<style>
#map {
  margin: 0 auto;
  height: 500px;
  width: 500px;
}
</style>

<script>
let map

let geocoder
// 下の1行を追加 
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.731005, lng:139.452995},
    zoom: 18,
  });

  marker = new google.maps.Marker({
    position:  {lat: 35.731005, lng:139.452995},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });

      display.textContent = "住所：" + results[ 0 ].formatted_address.replace(/^日本、/, '');
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.credentials[:google_api_key]%>&callback=initMap" async defer></script>

<script src="https://cdn.jsdelivr.net/clipboard.js/1.5.13/clipboard.min.js"></script>
 
<script>
var clipboard = new Clipboard('.copy_btn');    //clipboard.min.jsが動作する要素をクラス名で指定
 
//クリックしたときの挙動
// $(function(){
//     $('.copy_btn').click(function(){
        // $(this).addClass('copied');    //ボタンの色などを変更するためにクラスを追加
        // $(this).text('コピーしました');    //テキストの書き換え
//     });
// });
</script>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-color">
  <a href="/" >
    <span class="navbar-brand mb-0 header">
      <span class="en">¥</span>100!!!
    </span>
  </a>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="navbar-item">
        <%= link_to "レビュー閲覧", posts_path ,class:"nav-link" ,style:"color:white"%>
      </li>
      <li class="navbar-item">
        <%= link_to "レビュー投稿", new_post_path ,class:"nav-link" ,style:"color:white"%>
      </li>
      <li class="navbar-item">
        <%= link_to "ランキング", ranking_posts_path ,class:"nav-link" ,style:"color:white"%>
      </li>
      <li class="navbar-item">
        <%= link_to "ショップ検索", map_path ,class:"nav-link" ,style:"color:white"%>
      </li>
      <li class="nav-item dropdown mr-5">
        <a class="nav-link dropdown-toggle py-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white">
          <%= image_tag current_user.user_image.url, class:"user_icon"%>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "投稿一覧", posts_user_path(current_user),class:"dropdown-item"%>
          <%= link_to "買い物リスト", shoppings_user_path(current_user) ,class:"dropdown-item"%>
          <%= link_to "レビューした投稿", reviews_user_path(current_user) ,class:"dropdown-item"%>
          <%= link_to "アカウント編集", edit_user_registration_path ,class:"dropdown-item"%>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } ,class:"dropdown-item"%>
        <div>
      </li>
      <% else %>
        <li class="navbar-item text-right"><%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post %></li>
        <li class="navbar-item text-right"><%= link_to "ログイン", new_user_session_path %></li>
        <li class="navbar-item text-right"><%= link_to "アカウント登録", new_user_registration_path%></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HundredApp2</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
  
  <header>
    <%= render 'layouts/header'%>
  </header>
  <%= render 'layouts/flash'%>
  <div class="container">
    <%= yield %> 
  </div>  
  <footer class="fixed-bottom"  style="height: 2rem;">
    <nav class="navbar navbar-dark bg-color py-0">
      <span class="navbar-brand footer">Copyright  kazuki asano, 2021 All Rights Reserved.</span>
    </nav>
  </footer>
  </body>
</html>

app/views/posts/_post_button.html.erb
<% if current_page?(path) %>
  <%= link_to head,path,class:"btn btn-secondary col-4" %>
<% else %>
  <%= link_to head,path,class:"btn btn-outline-dark col-4" %>
<% end %>

app/views/posts/new.html.erb
<h2 class="text-center mt-3 mb-4">新規投稿</h2>
<%= render 'form' %>

app/views/posts/reviews.html.erb
<hr/>
<div class="mx-auto text-center my-4">
  <h4 class="mt-4"><%=@post.name%></h4>
  <div class="mb-3" style="opacity: 0.5;">
    <%if @post.user.name?%>
      投稿者: <%= @post.user.name%>さん
    <%else%>
      投稿者: 名無しさん
    <%end%>
  </div>
  <h4>
    <span id="rate<%=@post.id%>" class="mr-2"></span>
  </h4>
  <h4><%= @post.reviews.average(:rate) %></h4>
  <h5>(<%= @reviews.count%>件の口コミ)</h5>
</div>
<hr/>
<div class="container-fluid mx-auto mt-3 mb-5">
  <div class="row">
    <%= render partial: 'post_button', locals: { head:"投稿", path: post_path}%>
    <%= render partial: 'post_button', locals: { head:"口コミ", path: reviews_post_path}%>
    <%= render partial: 'post_button', locals: { head:"レビュー閲覧に戻る", path: posts_path}%>
  </div>
</div>
<script>
  $('#rate<%= @post.id %>').empty();
  $('#rate<%= @post.id%>').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf:  '<%= asset_path('star-half.png') %>',
    half      : true,
    readOnly: true,
    score: <%= @post.reviews.average(:rate).to_f.round(1) %>,
  });
</script>

<div class="card_container">
<%if @reviews.exists?%>
  <% @reviews.each do |review|%>
    <div class="card mb-3 px-4 py-3">
      <div class="row" >
        
          <%= image_tag review.user.user_image.url, class:"ml-2 reviewer_icon"%>
        
        <div class="col-2">
        </div>
        <div class="col-6">
          <h4>
            <%if review.user.name?%>
              <%= review.user.name%>
            <%else%>
              名無し
            <%end%>
          </h4>
          <%= review.shop_name%>
        </div>
      </div>
      <%if review.user_id==current_user.id%>
        <div class="mt-2">
          <%=link_to "編集", edit_review_path(review),class:"mr-3"%>
          <%=link_to "削除", post_reviews_path(post_id:review.post_id), method: :delete, data: { confirm: '削除してよろしいですか?' }%>
        </div>
      <%end%>
      <hr/>
      <div class="mb-2">
        <span id="star-rate<%=review.id%>" class="mr-2"></span>
        <span class="align-middle" style="font-size: 1.3rem;"><%=review.rate%></span>
      </div>
      <hr/>
      <h4><%=review.title%></h4>
      <%=review.comment%>
      <p class="text-right"><%= review.created_at.strftime('%Y/%m/%d')%></p>
      <script>
        $('#star-rate<%= review.id %>').empty();
        $('#star-rate<%= review.id%>').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf:  '<%= asset_path('star-half.png') %>',
          half      : true,
          readOnly: true,
          score: <%= review.rate %>,
        });
      </script>
    </div>
  <%end%>
<%else%>
  <h2>口コミがまだありません</h2>
<%end%>
</div>

app/views/posts/show.html.erb
<hr/>
<div class="row">
  <div class="col-8">
    <div style="display: inline; border:1px solid; padding: 0.2rem;">
      <%=@post.genre%>
    </div>
    <h4 class="my-2"><%=@post.name%></h4>
    <div class="mb-2">
      <span id="star-rate<%=@post.id%>" class="mr-2"></span>
      <span class="align-middle" style="font-size: 1.3rem;"><%=@post.rate%></span>
    </div>
    <div class="post_index_icon">
      <span class="mr-2"><i class="fas fa-shopping-cart mr-2"></i><%=@post.shoppings.count%>件</span>
      <span class="ml-3"><i class="fas fa-comments mr-2"></i><%=@post.reviews.count%>件</span>
    </div>
    <div class="mt-2" style="opacity: 0.5;">
      <%if @post.user.name?%>
        投稿者: <%= @post.user.name%>さん
      <%else%>
        投稿者: 名無しさん
      <%end%>
    </div>
  </div>
  </div>
  <div class="container-fluid mx-auto mt-3">
  <div class="row">
    <div class="col-4 px-0">
      <%= render 'shoppings/shopping' %>
    </div>
    <%if @post.user_id!=current_user.id%>
      <%if Review.exists?(user: current_user, post_id: @post.id)%>
        <div class="comment_done col-4">
          <i class="fas fa-comments mr-1"></i>口コミ投稿済
        </div>
      <%else%>
        <%= link_to new_post_reviews_path(@post),class: "col-4 px-0" do %>
          <div class="btn comment_button text-decoration-none">
            <i class="fas fa-comments mr-1"></i>口コミ投稿
          </div>
        <%end%>
      <%end%>
    <%end%>
    <%if @post.user_id==current_user.id%>
      <%= link_to edit_post_path(@post),class: "btn post_edit_button col-4" do%>
          投稿編集
      <%end%>
      <%= link_to post_path(@post), method: :delete, data: { confirm: '削除してよろしいですか?' } ,class: "btn post_delete_button col-4" do%>
        投稿削除
      <%end%>
    <%end%>
</div>
</div>
<hr/>
<div class="container-fluid mx-auto mt-3">
  <div class="row">
    <%= render partial: 'post_button', locals: { head:"投稿", path: post_path}%>
    <%= render partial: 'post_button', locals: { head:"口コミ", path: reviews_post_path}%>
    <%= render partial: 'post_button', locals: { head:"レビュー閲覧に戻る", path: posts_path}%>
  </div>
</div>

<div class="text-center my-5">
  <%= image_tag @post.image.url, class:"post_image mx-4 col-9", style:"height: 25rem; object-fit: cover;"%>
</div>

<table class="table">
  <tbody>
    <tr>
      <th scope="row" style="width: 20%; background-color: #F3D693;">購入店舗名</th>
      <td><%= @post.shop_name%></td>
    </tr>
    <tr>
      <th scope="row" style="width: 20%; background-color: #F3D693;">購入回数</th>
      <td>
        <%if @post.purchase_num%>
          初めて
        <%else%>
          2回以上
        <%end%>
      </td>
    </tr>
    <tr>
      <th scope="row" style="width: 20%; background-color: #F3D693;">投稿者コメント</th>
      <td><%=@post.comment%></td>
    </tr>
  </tbody>
</table>
<%# <p>みんなの口コミ</p> %>

<script>
  $('#star-rate<%= @post.id %>').empty();
  $('#star-rate<%= @post.id%>').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf:  '<%= asset_path('star-half.png') %>',
    half      : true,
    readOnly: true,
    score: <%= @post.rate %>,
  });
  </script>

app/views/shoppings/_shopping.html.erb
<div id="shopping-<%= @post.id%>">
    <% if Shopping.exists?(user: current_user, post_id: @post.id) %>
      <%= link_to "/posts/#{@post.id}/shoppings", class: "btn shopping_out_button", method: :delete, remote: true do %>
        <div><i class="fas fa-arrow-alt-circle-left mr-1"></i>カゴから出す</div>
      <%end%>
    <% else %>
      <%= link_to "/posts/#{@post.id}/shoppings", class: "btn shopping_in_button", method: :post, remote: true do %>
        <div><i class="fas fa-shopping-cart mr-1"></i>カゴに入れる</div>
      <%end%>
    <% end %>
  </div>

app/views/shoppings/create.js.erb
$("#shopping-<%= @post.id %>").html("<%= j(render partial: 'shoppings/shopping', locals: { post: @post }) %>");

app/views/shoppings/destroy.js.erb
$("#shopping-<%= @post.id %>").html("<%= j(render partial: 'shoppings/shopping', locals: { post: @post }) %>");

app/views/users/_user_info.html.erb
<div class="card my-5">
  <div class="card-body">
    <div class="row mx-2">
      <%= image_tag @user.user_image.url, class:"mypage_user_icon"%>
      <div class="col-2">
      </div>
      <div class="col-6">
        <h3 class="card-title">
          <% if @user.name? %>
            <%= @user.name%>さんのマイページ
          <% else %>
            名無しさんのマイページ
          <% end %>
        </h3>
        <hr class="mb-2">
        <p class="mb-1 m-0">よく利用する100円ショップ</p>
        <p>
          <% if @user.favoshop? %>
            <%=@user.favoshop%>
          <% else %>
            なし
          <% end %>
        </p>
      </div>
    </div>
    <div class="container-fluid mx-auto mt-3">
      <div class="row">
        <%= render partial: 'user_button', locals: { head:"投稿一覧", path: posts_user_path}%>
        <%= render partial: 'user_button', locals: { head:"買い物リスト", path: shoppings_user_path}%>
        <%= render partial: 'user_button', locals: { head:"レビューした投稿", path: reviews_user_path}%>
        <%= render partial: 'user_button', locals: { head:"アカウント編集", path: edit_user_registration_path}%>
      </div>
    </div>
  </div>
</div>